version: "3"
services:
  test_app1:
    build:
      context: ./packages/email-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - mongodb

  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "9100:80"
    depends_on: 
      - test_app1

  mongodb:
    restart: "always"
    container_name: "mongodb"
    build: 
      context: ./mongodb
      dockerfile: Dockerfile
    ports:
      - "27017:27017"