version: "3"
services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "9100:80"
    depends_on: 
      - test_app1

  test_app1:
    build:
      context: ./packages/email-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"

  # mongo:
  #   restart: "always"
  #   container_name: "mongodb"
  #   image: "mongo:latest"
  #   volumes:
  #     - "mongodb:/data/db/"
  #   ports:
  #     - "27017:27017"

# volumes:
#   mongodb: