version: "3"
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "9100:80"
  # app: 
  #   build:
  #     context: ./app
  #     dockerfile: ./packages/email-service/Dockerfile
  #     expose:
  #       - 8080
  
  # mongo:
  #   restart: "always"
  #   container_name: "mongodb"
  #   image: "mongo:latest"
  #   volumes:
  #     - "mongodb:/data/db/"
  #   ports:
  #     - "27017:27017"

# volumes:
#   mongodb: